---
# WireGuard & SOC Hub Network Parameters
soc_hub_wg_ip: "10.100.0.1"
node_wg_ip: "10.100.0.2"
wg_server_pubkey: "{{ vault_wg_server_pubkey }}"
wg_node_privkey: "{{ vault_wg_node_privkey }}"
wg_interface: "wg0"
wg_port: 51820

# CIS Hardening Parameters
rhel9_cis_level_1: true
rhel9_cis_time_servers: ["pool.ntp.org"]
